version: "3.9"
services:
  backend:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.backend
    container_name: ai-ia-backend
    environment:
      - DOUBAO_API_BASE=${DOUBAO_API_BASE:-https://ark.cn-beijing.volces.com/api/v3}
      - DOUBAO_API_KEY=${DOUBAO_API_KEY}
      - DOUBAO_MODEL=${DOUBAO_MODEL:-ep-xxxxxxxx}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT:-你是一个专业的面试官，擅长结构化提问与基于STAR法的追问，回答请简洁、条理清晰，并在必要时给出改进建议。}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.frontend
    container_name: ai-ia-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE=/api
    # Frontend nginx will proxy /api to backend service via internal DNS name
    links:
      - backend

networks:
  default:
    name: ai-interview-assistant-net
